version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: latte
      POSTGRES_PASSWORD: latte
      POSTGRES_DB: frappuccino
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U latte -d frappuccino"]
      interval: 5s
      timeout: 5s
      retries: 5
    
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: latte
      DB_PASSWORD: latte
      DB_NAME: frappuccino
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data: