version: '3.8'

services:
  db:
    image: postgres:15
    container_name: frappuccino_db
    environment:
      POSTGRES_USER: latte
      POSTGRES_PASSWORD: latte
      POSTGRES_DB: frappuccino
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql 
      
    restart: always

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frappuccino_app
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: latte
      DB_PASSWORD: latte
      DB_NAME: frappuccino
    restart: always